package com.leonardo.springbootdemo.mapper;

import com.leonardo.springbootdemo.entity.ResourceInfo;

import java.util.List;

public interface ResourceInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_info
     *
     * @mbg.generated
     */
    int insert(ResourceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_info
     *
     * @mbg.generated
     */
    int insertSelective(ResourceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_info
     *
     * @mbg.generated
     */
    ResourceInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ResourceInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resource_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ResourceInfo record);

    List<ResourceInfo> getAllResources();
}